# Generated by Django 3.2.16 on 2024-10-06 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20241004_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Create',
        ),
    ]
